## get request for Nest app

GET http://localhost:3000/users/1234
?limit=10
&page=1

# Post request for Nest app

// IMPORTANT: This is a POST USER request
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@gmail.com",
  "password": "12345678Tt@"
}

// MARK: This is a PATCH USER request
PATCH http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@gmail.com",
}
