## get request for Nest app

GET http://localhost:3000/users/12
?limit=kl
&page=1

# Post request for Nest app

POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@gmail.com",
  "password": "12345678"
}
