POST http://localhost:3000/posts
Content-Type: application/json 

{
  "title": "whats new in NestJS",
  "postType": "post",
  "slug": "new-with-nestjs",
  "status": "draft",
  "content": "test content",
   "schema": "{\"type\":\"object\"}",     
  "featuredImageUrl": "https://example.com/image.jpg",
  "publishOn": "2025-10-01T00:00:00Z",
  // "tags": ["nestjs", "typescript", "backend"],
  "metaOptions": {
     "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
  }

}


// MARK: PATCH /posts

PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 1234,
  "postType": "post"

}
